<?php

 
  function winsports_video_export_menu() {
    
    $items = array();
    
    $items['winsports-video-export/%'] = array(
	'access arguments' => array( 'access content' ),
	'page arguments'   => array( 1 ),
	'page callback'    => 'winsports_video_export_iframe_load',
	'title'            => t('Exportar video'),
	'type'             => MENU_CALLBACK,
    );
    
    return $items;
    
  }
  


  function winefecty_totals_block_info() {
    
    $blocks = array();

    $blocks['totals'] = array(
	'cache' => DRUPAL_CACHE_GLOBAL,
	'info'  => t('Totales'),
    );

    return $blocks;
    
  }
  

  
  function winefecty_totals_block_view( $delta = '' ) {
    
    $blocks = array();

    if ( $delta == 'totals' ) {
	$blocks['subject'] = t('totales');
	$blocks['content'] = winefecty_totals_callback();
    }

    return $blocks;
    
  }
  
  
  function winefecty_totals_callback() {

    $output = '';
    
    $queryUsers = db_select( 'users', 'u' )
	    ->fields( 'u' )
	    ->execute()
	    ->rowCount();
    
    $queryAnswer = db_select( 'node', 'n' )
	    ->fields( 'n' )
	    ->condition( 'n.type', 'user_answer', '=' )
	    ->execute()
	    ->rowCount();
    
    $output .= '<div><strong><em>Total de usuarios: ' . $queryUsers . '</em></strong></div>';
    $output .= '<div><strong><em>Total de respuestas: ' . $queryAnswer . '</em></strong></div>';
    
    return $output;
    
  }
  
  
  
  