<?php

 
  function winefecty_totals_block_info() {
    
    $blocks = array();

    $blocks['totals'] = array(
	'cache' => DRUPAL_CACHE_GLOBAL,
	'info'  => t('Totales'),
    );

    return $blocks;
    
  }
  

  
  function winefecty_totals_block_view( $delta = '' ) {
    
    $blocks = array();

    if ( $delta == 'totals' ) {
	$blocks['subject'] = t('totales');
	$blocks['content'] = winefecty_totals_callback();
    }

    return $blocks;
    
  }
  
  
  function winefecty_totals_callback() {

    $output = '';
    
    $queryUsers = db_select( 'users', 'u' )
	    ->fields( 'u' )
	    ->execute()
	    ->rowCount();
    
    $queryAnswer = db_select( 'node', 'n' )
	    ->fields( 'n' )
	    ->condition( 'n.type', 'user_answers', '=' )
	    ->execute()
	    ->rowCount();
    
    $output .= '<div><strong><em>Total de usuarios: ' . $queryUsers . '</em></strong></div>';
    $output .= '<div><strong><em>Total de respuestas: ' . $queryAnswer . '</em></strong></div>';
    
    return $output;
    
  }
  
  
  
  